# Generated by Django 3.1.7 on 2021-05-14 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('datetime', models.DateTimeField(default='14.05.2021 10:43:53')),
                ('message', models.CharField(max_length=300)),
            ],
        ),
    ]
