# Generated by Django 3.1.7 on 2021-05-16 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doomer', '0003_auto_20210514_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='datetime',
            field=models.CharField(max_length=64),
        ),
    ]
