# Generated by Django 3.1.7 on 2021-05-22 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doomer', '0004_auto_20210516_1813'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donateId', models.CharField(max_length=16)),
                ('datetime', models.CharField(max_length=64)),
                ('username', models.CharField(max_length=64)),
                ('message', models.CharField(max_length=300)),
                ('amount', models.CharField(max_length=32)),
                ('currency', models.CharField(max_length=16)),
            ],
        ),
    ]
